stages:
  - build

before_script:
  - "mvn clean install -U"

test:
  stage: build
  script:
  - "mvn test"
  except:
    - release
    - master

artefacts:
  stage: build
  script:
  - "mvn package -DskipTests"
  artifacts:
    name: "$CI_BUILD_REF_NAME"
    expire_in: '1 yrs'
    paths:
    - "target/*.jar"
  only:
    - release
    - master