language: java
jdk:
  - openjdk8
sudo: false
notifications:
  email:
    on_failure: always
    on_success: never
deploy:
  provider: releases
  file:
    - "./target/ChunkGuard*.jar"
  skip_cleanup: true
  on:
    tags: true
    repo: yannicklamprecht/ChunkGuard
  overwrite: true
